repositoryUrl: https://github.com/Dynamsoft/barcode-reader-docs/blob/master
repository: Dynamsoft/barcode-reader-docs
docFullPath: https://www.dynamsoft.com/barcode-reader
firstLevelUrl: /barcode-reader
docHomePage: /barcode-reader/programming/

productUrl: https://www.dynamsoft.com/Products/Dynamic-Barcode-Reader.aspx
productName: Dynamsoft Barcode Reader

introduction: /barcode-reader/introduction/
programming: /barcode-reader/programming/
parameters: /barcode-reader/parameters/
license_activation: /barcode-reader/license-activation/
enhancements: /barcode-reader/enhancements/

comparison_tools: /barcode-reader/introduction/comparison-tools/

c_cplusplus: /barcode-reader/programming/c-cplusplus/
structs: /barcode-reader/programming/c-cplusplus/struct/

c: /barcode-reader/programming/c/
c_api: /barcode-reader/programming/c/api-reference/
c_methods: /barcode-reader/programming/c/api-reference/methods/
c_release_notes: /barcode-reader/programming/c/release-notes/

cpp: /barcode-reader/programming/cplusplus/
cpp_api: /barcode-reader/programming/cplusplus/api-reference/
cpp_methods: /barcode-reader/programming/cplusplus/api-reference/cbarcodereader-methods/
cpp_release_notes: /barcode-reader/programming/cplusplus/release-notes/

js: /barcode-reader/programming/javascript/
js_api: /barcode-reader/programming/javascript/api-reference/
js_release_notes: /barcode-reader/programming/javascript/release-notes/

dotnet: /barcode-reader/programming/dotnet/
dotnet_api: /barcode-reader/programming/dotnet/api-reference/
dotnet_release_notes: /barcode-reader/programming/dotnet/release-notes/

oc: /barcode-reader/programming/objectivec-swift/
oc_api: /barcode-reader/programming/objectivec-swift/api-reference/
oc_release_notes: /barcode-reader/programming/objectivec-swift/release-notes/
oc_class: /barcode-reader/programming/objectivec-swift/api-reference/class/
oc_methods: /barcode-reader/programming/objectivec-swift/api-reference/methods/

java: /barcode-reader/programming/java/
java_api: /barcode-reader/programming/java/api-reference/
java_release_notes: /barcode-reader/programming/java/release-notes/

android: /barcode-reader/programming/android/
android_api: /barcode-reader/programming/android/api-reference/
android_release_notes: /barcode-reader/programming/android/release-notes/
android_class: /barcode-reader/programming/android/api-reference/class/
android_methods: /barcode-reader/programming/android/api-reference/methods/
  
python: /barcode-reader/programming/python/
python_api: /barcode-reader/programming/python/api-reference/
python_release_notes: /barcode-reader/programming/python/release-notes/

parameters_reference: /barcode-reader/parameters/reference/
scenario_settings: /barcode-reader/parameters/scenario-settings/
enumerations: /barcode-reader/parameters/enum/

faqs: /barcode-reader/introduction/faqs.html
how_to: /barcode-reader/introduction/how-to-guide/

assets: /barcode-reader/assets/
edit_icon: /barcode-reader/assets/img-icon/edit-icon.png
smile_icon: /barcode-reader/assets/img-icon/icon-smile.png
sad_icon: /barcode-reader/assets/img-icon/icon-sad.png
dbr_icon: /barcode-reader/assets/img-icon/icon-dbr.svg
dwt_icon: /barcode-reader/assets/img-icon/icon-dwt.svg
dnt_icon: /barcode-reader/assets/img-icon/icon-dnt.svg

baseurl: "/barcode-reader"
plugins:
  - jemoji